### ISSUE TITLE
Wrap MMR Proof with ZKP

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/research#17]
## Desc

Might be a solution for the crazy gas fee in Ethereum ( claim 30 KTON takes around 242$ )

---

Wed Feb 17 03:34:53 CST 2021

**Comment by hackfisher** [comment]
Stale and unclear, but we definitely can do some optimization for ethereum gas fee, might be commitment enhancement recently, stay unknown for zkp solutions.

Closing it.
