### ISSUE TITLE
Design a super light client friendly consensus for darwinia

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/research#7]
So we can develop chain relay for darwinia on other public blockchain more easily and with less cost and complexity.

**Comment by acgxv** [comment]
## Resources

### Existed Project
- [beam](https://github.com/BeamMW/beam) (Fly Client)
	- [Sampling strategy](https://github.com/BeamMW/beam/blob/master/core/chainwork.cpp) is according to the following logic:
		1. Sample a point within the first 1/N of the asserted chainwork range.
		2. Verify the proof for this point.
		3. Cut-off the range from the beginning to the current point, and continue to (a)
- [grin](https://github.com/mimblewimble/grin) (Fly Client)
	- issue tracking: https://github.com/mimblewimble/grin/issues/1555
- [zcash](https://github.com/zcash/zips) (Fly Client)
	- design: [zip-0221.rst](https://github.com/therealyingtong/zips/blob/master/zip-0221.rst)
	- PR tracking: https://github.com/zcash/zips/pull/220

### Intro
- [Block Quick v.s. Fly Client](https://diode.io/burning-platform-pki/blockquick-super-light-blockchain-client-for-trustless-time-19144)
- [Fly Client and Merkle Mountain Ranges](https://etcsummit.com/wp-content/uploads/2019/10/ETC-Summit-2019-Day-1-Talk-07-Zac-Mitton-Adding-Merkle-Mountain-Ranges-and-Fly-Proofs-to-ETC.pdf)
	- [107 - Zac Mitton - Adding Merkle Mountain Ranges and Fly Proofs to ETC](https://www.youtube.com/watch?v=uA1dw1qDytM&t=639s&ab_channel=ETCCooperative)
- [Fly Client Scaling Bitcoin](https://stanford2017.scalingbitcoin.org/files/Day1/flyclientscalingbitcoin.pptx.pdf)
	- [Flyclient: Super-Light Clients for Cryptocurrencies - Benedikt Bünz](https://www.youtube.com/watch?v=vuzYwutBqjY)
	- [Scaling Bitcoin 2017 Stanford University - Day 1 Morning](https://www.youtube.com/watch?time_continue=8404&v=BPNs9EVxWrA)

### Paper
- [Block Quick](https://eprint.iacr.org/2019/579.pdf)
- [Fly Client](https://eprint.iacr.org/2019/226.pdf)
- [MMR](https://eprint.iacr.org/2015/718.pdf)

**Comment by hackfisher** [comment]
https://github.com/darwinia-network/rfcs/pull/29/files#diff-9ec79b8a57deb49fb34d81e357c28088R280

**Comment by hackfisher** [comment]
Grandpa light client solution can meet this requirement,

And beefy for non-substrate bridge supports:
https://github.com/paritytech/grandpa-bridge-gadget
